id: opecha:P007130
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18877
  title: ཆུ་ཡི་སྦགས་བཙོག་འགོག་སེལ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  volume:
    5cea23f934b845a48702729e9d407fb1:
      image_group_id: I8LS18879
      title: Volume 1 of chu yi sbags btsog 'gog sel byed phyogs skor gyi krung hwa
        mi dmangs spyi mthun rgyal khab kyi bca' khrims/
      volume_number: 1
      total_pages: 78
  author: ''
ebook_metadata:
  title: ཆུ་ཡི་སྦགས་བཙོག་འགོག་སེལ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  sku: P007130
  cover: cover.jpg
  layers:
  - pagination
