id: P007130
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18877
  title: ཆུ་ཡི་སྦགས་བཙོག་འགོག་སེལ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    c09c81d82d184952b1991cce2af10d05:
      image_group_id: I8LS18879
      title: ''
      volume_number: 1
      total_pages: 78
ebook_metadata:
  title: ཆུ་ཡི་སྦགས་བཙོག་འགོག་སེལ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  sku: P007130
  cover: cover.jpg
  layers:
  - pagination
