id: P007130
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:43:41.072533
source_metadata:
  id: bdr:W8LS18877
  title: ཆུ་ཡི་སྦགས་བཙོག་འགོག་སེལ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    5cea23f934b845a48702729e9d407fb1:
      image_group_id: I8LS18879
      title: Volume 1 of chu yi sbags btsog 'gog sel byed phyogs skor gyi krung hwa
        mi dmangs spyi mthun rgyal khab kyi bca' khrims/
      volume_number: 1
      total_pages: 78
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
