id: ID120FDC2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:52:36+00:00'
last_modified: '2022-06-09T06:18:16.988724+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18877
  title: ཆུ་ཡི་སྦགས་བཙོག་འགོག་སེལ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    78CA:
      image_group_id: I8LS18879
      title: Volume 1 of chu yi sbags btsog 'gog sel byed phyogs skor gyi krung hwa
        mi dmangs spyi mthun rgyal khab kyi bca' khrims/
      total_pages: 78
      order: 1
      base_file: 78CA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
